ALTER TYPE "LedgerSourceType" ADD VALUE IF NOT EXISTS 'CONTRACT_PURCHASE';

ALTER TABLE "VehicleCost"
ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX "VehicleCost_documentId_autoGenerated_idx"
ON "VehicleCost"("documentId", "autoGenerated");
